### ISSUE TITLE
Error when running Programmatic mode example 

### ISSUE THREAD

**Issue by adubredu** [thiagopbueno/rddl2tf#15]
After freshly installing `rddl2tf`  in a new conda environment, I am unable to run the  Programmatic mode example in the README. 

I get the following error

`Traceback (most recent call last):
  File "testtf.py", line 8, in <module>
    compiler = Compiler(model)
TypeError: Can't instantiate abstract class Compiler with abstract methods _compile_aggregation_expression, _compile_arithmetic_expression, _compile_boolean_expression, _compile_constant_expression, _compile_control_flow_expression, _compile_function_expression, _compile_pvariable_expression, _compile_random_variable_expression, _compile_relational_expression`

**Comment by thiagopbueno** [comment]
Hi @alphonsusadubredu 

Hope you're doing well. Thanks for your interest in my rddl2tf package.

Indeed, the documentation (and also the script `rddl2tf`) needed to be updated to the new, streamlined API. More specifically, the issue you encountered was due to the fact that now the `Compiler` class is an abstract base class and you might use the `DefaultCompiler` instead.

Please reinstall the `rddl2tf` package (check with `rddl2tf --help` to make sure you got v0.5.13) and check the updated README out.

Let me know if this quick fix solves the issue and please don't hesitate to send a message or open an issue if you find other difficulties.

Cheers,
Thiago
